baseURL: https://example.com/
languageCode: en-us
title: A Hugo theme for creating Reveal.js presentations
disableKinds:
  - sitemap
  - RSS
theme: reveal-hugo
author:
  name: Josh Dzielak
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
    style: tango
outputFormats:
  Reveal:
    baseName: index
    isHTML: yes
    mediaType: text/html
params:
  reveal_hugo:
    history: yes
    templates:
      grey:
        background: '#424242'
        transition: convex
