baseurl: https://example.com/
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: no
  contentTypeName: post
  fullWidthTheme: yes
  showMenuItems: 2
  themeColor: green
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: showcase
          name: Showcase
          url: /showcase
    menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: Portfolio - Sanskriti Bajaj
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: Find all my data analytics projects here
    title: Portfolio - Sanskriti Bajaj
